inhibit_all_warnings!

platform :ios, '9.0'

source 'https://github.com/elegion/ios-podspecs.git'

def pod_list
    pod 'Ailen', '0.0.1.alpha.3'
end

target 'AilenDBOutput' do
	use_frameworks!

    pod_list
end


target 'AilenDBOutputTests' do
    use_frameworks!
    
    pod_list
    
end
